### PR TITLE
ios not recognized

### PR DESCRIPTION
**Pull request by puran2**
ios devices are not recognized. I have changed Ipad; U; -> Ipad; and so on.

### CODE REVIEW

**Comment by isocroft** [comment]
@puran2 thanks for your pull request. I really appreciate them. However, here are the standard user-agent strings for **iPad** and **iPhone**

**For IPAD -> Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.10**

**For IPHONE -> Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A293 Safari/6531.22.7**

So, i was wondering why you took out the _U;_ part from the sub-string sentinel for detection. Can i have your reply to this here ?

The wrong characters "x" are a mistake by me and you made the timely adjustments to it. Thanks a lot for that!!

**Comment by puran2** [comment]
My user-agent string starts with Mozilla/5.0 (IPad; CPU .... ( look attachment ). Is the same on the IPhone and on a new IPad.

img_0044

**Comment by isocroft** [comment]
Super Duper!!! Thanks a millie! I missed this one totally. Your fix will very well do.

Thanks once again.

**Comment by isocroft** [comment]
Merged

**Pull request merged**
